name: ccnn
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.9
  - h5py
  - matplotlib
  - torchaudio
  - pytorch
  - cudatoolkit=11.3
  - torchvision
  - torchtext
  - plotly
  - pip
  - pip:
    - hydra-core
    - wandb
    - datasets
    - pytorch-lightning
